'''
hand written descriptor for the socket module
'''
from .descriptor import ModuleDescriptor

def get_descriptors():
    return build_socket(), 

def build_socket(des = None):
    if des is None:
        des = ModuleDescriptor('socket')
    des.add_module('socket')
    des.add_module('_socket')
    des.add_module('select') #pyd
    #
    des.add_dependency('selectors')
    des.add_dependency('enum')
    des.add_dependency('tokenize')
    des.add_dependency('token')
    des.add_dependency('ast')
    des.add_dependency('shlex')
    des.add_dependency('tarfile')
    des.add_dependency('pdb')
    des.add_dependency('argparse')
    des.add_dependency('doctest')
    des.add_dependency('shutil')
    des.add_dependency('plistlib')
    des.add_dependency('gzip')
    des.add_dependency('datetime')
    des.add_dependency('optparse')
    des.add_dependency('_hashlib')
    des.add_dependency('dummy_threading')
    des.add_dependency('glob')
    des.add_dependency('ssl')
    des.add_dependency('gettext')
    des.add_dependency('getopt')
    des.add_dependency('_lzma')
    des.add_dependency('textwrap')
    des.add_dependency('_dummy_thread')
    des.add_dependency('__future__')
    des.add_dependency('posixpath')
    des.add_dependency('urllib')
    des.add_dependency('subprocess')
    des.add_dependency('html')
    des.add_dependency('copy')
    des.add_dependency('zipfile')
    des.add_dependency('_compression')
    des.add_dependency('struct')
    des.add_dependency('_ssl')
    des.add_dependency('xml')
    des.add_dependency('cmd')
    des.add_dependency('_bz2')
    des.add_dependency('codeop')
    des.add_dependency('pydoc')
    des.add_dependency('bz2')
    des.add_dependency('bdb')
    des.add_dependency('pkgutil')
    des.add_dependency('hashlib')
    des.add_dependency('logging')
    des.add_dependency('py_compile')
    des.add_dependency('platform')
    des.add_dependency('bisect')
    des.add_dependency('email')
    des.add_dependency('random')
    des.add_dependency('tracemalloc')
    des.add_dependency('unittest')
    des.add_dependency('tempfile')
    des.add_dependency('difflib')
    des.add_dependency('webbrowser')
    des.add_dependency('uu')
    des.add_dependency('signal')
    des.add_dependency('pprint')
    des.add_dependency('fnmatch')
    des.add_dependency('inspect')
    des.add_dependency('_strptime')
    des.add_dependency('base64')
    des.add_dependency('lzma')
    des.add_dependency('ipaddress')
    des.add_dependency('mimetypes')
    des.add_dependency('http')
    des.add_dependency('threading')
    des.add_dependency('_threading_local')
    des.add_dependency('pyexpat')
    des.add_dependency('dis')
    des.add_dependency('socketserver')
    des.add_dependency('calendar')
    des.add_dependency('pydoc_data')
    des.add_dependency('code')
    des.add_dependency('opcode')
    des.add_dependency('quopri')
    des.add_dependency('string')

    return des